./: \
  base \
  mesh_provider \
  scene_graph \
  misc \
  python_bindings

lib{paracadis}: \
  lib{base} \
  lib{mesh_provider} \
  lib{scene_graph} \
  lib{misc} \
  lib{python_bindings}

import pkg-config

add_project_arguments('-DCGAL_HAS_THREADS', language : 'cpp')

deps = [
  dependency('CGAL'),
  dependency('openmp'),
  dependency('gmpxx'),
  dependency('mpfr'),
]

test_deps = [
  dependency('catch2'),
  dependency('catch2-with-main'),
]

test_main_src = files('cpp_test.cpp')

