import libs  = libparacadis%lib{paracadis}
import libs += pybind11%lib{pybind11}
import libs += python3%lib{python3}

# I should not have to use this here! :-(
# It should be resolved, IMO, by lib{paracadis} export.
import libs += libgeo_types%lib{geo_types}

info "Install root: $(config.install.root)."
root = [dir_path] "$(config.install.root)"
module_name = "pyracadis$(config.pyracadis.python_module_suffix)"
module_abs_dir = $(config.pyracadis.python_module_dir)
module_dir = $path.relative($module_abs_dir, $(root))

libs{pyracadis}: {mxx cxx}{** -***/tests/**} $libs
{
  install = $(module_dir)/$(module_name)
}
