import libs  = libparacadis%lib{paracadis}
import libs += pybind11%lib{pybind11}
import libs += python3%lib{python3}

lib{pyracadis}: $libs
{
  extension = shared
  name = pyracadis$(python-ext-suffix)
  install = true
  install.root = $(config.python-module-dir)
}

lib{pyracadis}: {mxx cxx}{** -***/build/** -***/tests/**}
