#!/bin/bash
exec 2> /home/andre/format.log

set -x
BIN="$(whereis -b -B /usr/bin/ -f -g 'clang-format-[0-9][0-9]' | cut -d ' ' -f 2)"

is_stdin="yes"
is_h_file="no"
for a in "$@"; do
  if [ -e "$a" ]; then
    is_stdin="no"
    filename="$a"
  fi

  case "$a" in
    *.h)
      is_h_file="yes"
      break
      ;;
  esac
done

if [ "$is_stdin" == "yes" ]; then
  temp_file="$(mktemp)"
  filename="$temp_file"
  trap 'rm -f -- "$temp_file"' EXIT
  cat > "$temp_file"
  if grep -q '^#define.*_H$' "$temp_file"; then
    is_h_file="yes"
  fi
fi

function exec_bin() {
  if [ "$is_stdin" == "yes" ]; then
    cat "$temp_file" | "$BIN" "$@"
    exit "${PIPESTATUS[-1]}"
  else
    "$BIN" "$@"
    exit "$?"
  fi
}

if [ "$is_h_file" == "no" ]; then
  exec_bin "$@"
fi

args=()
style_arg="-style=file:.clang-format_h"
has_style="no"
for a in "$@"; do
  case "$a" in
    -style=file)
      args+=("$style_arg")
      has_style="yes"
    ;;
    *)
      args+=("$a")
    ;;
  esac
done

if [ "$has_style" == "no" ]; then
  args+=("$style_arg")
fi

exec_bin "${args[@]}"
