import libs  = libgismo%lib{gismo}
import libs += libcgal%lib{cgal}
import libs += OGRE%lib{OgreMain}
import libs += OGRE-Bites%lib{OgreBites}
import libs += OGRE-RTShaderSystem%lib{OgreRTShaderSystem}
import libs += OGRE-Overlay%lib{OgreOverlay}

lib{paracadis}: {h hxx mxx cxx}{**} $libs
{
#  cxx.export.libs =
}

#for d: base scene_graph mesh_provider
#{
#  include $d/
#  lib{paracadis}: $d/lib{$d}
#  {
#    cxx.export.libs += $d/lib{$d}
#  }
#}

if ($cxx.target.system != 'win32-msvc')
{
  cxx.libs += -pthread
}

lib{paracadis}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
}
