import libs  = gismo%lib{gismo}
import libs += OGRE%lib{OgreMain}
import libs += OGRE-Bites%lib{OgreBites}
import libs += OGRE-RTShaderSystem%lib{OgreRTShaderSystem}

lib{scene_graph}: {mxx cxx}{*} $libs
